/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package planificacioncpu;


public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuFCFS = new javax.swing.JMenu();
        menuSJF = new javax.swing.JMenu();
        menuROUNDROBIN = new javax.swing.JMenu();
        menuMEMORIA = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jMenuBar1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jMenu1.setText("Inicio");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Planificacion");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        menuFCFS.setText("FCFS");
        menuFCFS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFCFSMouseClicked(evt);
            }
        });
        jMenu2.add(menuFCFS);

        menuSJF.setText("SJF");
        menuSJF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSJFMouseClicked(evt);
            }
        });
        menuSJF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSJFActionPerformed(evt);
            }
        });
        jMenu2.add(menuSJF);

        menuROUNDROBIN.setText("Round Robin");
        menuROUNDROBIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuROUNDROBINMouseClicked(evt);
            }
        });
        menuROUNDROBIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuROUNDROBINActionPerformed(evt);
            }
        });
        jMenu2.add(menuROUNDROBIN);

        menuMEMORIA.setText("Memoria");
        menuMEMORIA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMEMORIAMouseClicked(evt);
            }
        });
        jMenu2.add(menuMEMORIA);

        jMenuBar1.add(jMenu2);

        jMenu10.setText("Ayuda");

        jMenu13.setText("Manual");
        jMenu10.add(jMenu13);

        jMenu12.setText("Acerca de...");
        jMenu12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu12MouseClicked(evt);
            }
        });
        jMenu10.add(jMenu12);

        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
            
    }//GEN-LAST:event_jMenu2MouseClicked

    private void menuFCFSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFCFSMouseClicked
        // TODO add your handling code here:
        FCFS f=new FCFS();
        f.setVisible(true);
    }//GEN-LAST:event_menuFCFSMouseClicked

    private void menuSJFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSJFMouseClicked
        // TODO add your handling code here:
        SJF f=new SJF();
        f.setVisible(true);
    }//GEN-LAST:event_menuSJFMouseClicked

    private void menuROUNDROBINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuROUNDROBINMouseClicked
        // TODO add your handling code here:
        planificador rr = new planificador();
        rr.setVisible(true);
    }//GEN-LAST:event_menuROUNDROBINMouseClicked

    private void jMenu12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu12MouseClicked
        // TODO add your handling code here:
        AcercaDe f=new AcercaDe();
        f.setVisible(true);
    }//GEN-LAST:event_jMenu12MouseClicked

    private void menuMEMORIAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMEMORIAMouseClicked
        // TODO add your handling code here:
        Memoria f=new Memoria();
        f.setVisible(true);
    }//GEN-LAST:event_menuMEMORIAMouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void menuROUNDROBINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuROUNDROBINActionPerformed
        
    }//GEN-LAST:event_menuROUNDROBINActionPerformed

    private void menuSJFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSJFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSJFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuFCFS;
    private javax.swing.JMenu menuMEMORIA;
    private javax.swing.JMenu menuROUNDROBIN;
    private javax.swing.JMenu menuSJF;
    // End of variables declaration//GEN-END:variables
}
